codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # Basic settings
        target: auto
        threshold: 1%
        base: auto
        # Advanced settings
        branches: null
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
<<<<<<< HEAD
        # Basic settings
        target: auto
        threshold: 1%
        base: auto
        # Advanced settings
        branches: null
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
=======
        # basic
        target: auto
        threshold: 0.5%
        base: auto
>>>>>>> ae297e19e4ea9b26be75fbfe5c7487c0f497eab5

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
<<<<<<< HEAD
  require_head: yes

ignore:
  - "**/*.stories.{js,jsx,ts,tsx}"
  - "**/*.d.ts"
  - "src/types/**/*" 
=======
  require_head: yes 
>>>>>>> ae297e19e4ea9b26be75fbfe5c7487c0f497eab5
